import '@/styles/style.scss'
import '@/scripts/components/header.js'
import '@/images/svg/moon.svg'
import '@/images/svg/burger.svg'
import '@/images/Footer/logo.jpg'
import '@/images/Header/right.jpg'
import '@/images/Header/left.png'